# Generated by Django 4.2.6 on 2023-10-23 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('desc', models.TextField(max_length=250, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='User Name')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date create')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users_and_groups.group')),
            ],
        ),
    ]
